import React, { useState, useRef, useEffect } from 'react'
import { FaChevronRight, FaTrashAlt, FaCamera, FaKeyboard, FaSearch, FaHistory } from 'react-icons/fa'
import { v4 as uuidv4 } from 'uuid'
import { signLanguagePrompt } from './prompt.js'

export default function ChatBox() {
  const apiBase = process.env.REACT_APP_GESTURE_API || 'http://localhost:5001'
  const hasAutoGeneratedRef = useRef(false)
  const [input, setInput] = useState('')
  const [isCamOpen, setIsCamOpen] = useState(false)
  const [detectedText, setDetectedText] = useState('Waiting for sign language signal...')
  const [messages, setMessages] = useState([])
  const [isGenerating, setIsGenerating] = useState(false)
  const [genError, setGenError] = useState('')
  const [selectedWords, setSelectedWords] = useState([])
  const [signWords, setSignWords] = useState([])
  
  // Left side sign language conversion history (corresponding to the left side of Figure 3)
  const [history, setHistory] = useState([
    { id: '1', text: '我上課', time: '10:30' },
    { id: '2', text: '謝謝你', time: '09:15' }
  ])

  useEffect(() => {
    if (!isCamOpen) return
    let stopped = false
    let timeoutId = null

    const pollGesture = async () => {
      if (stopped) return
      try {
        const resp = await fetch(`${apiBase}/gesture`)
        if (!resp.ok) throw new Error('Gesture API not available')
        const data = await resp.json()
        const sequenceText = (data?.sequence_gesture_text || '').trim()
        const handText = (data?.hand_sign_text || '').trim()
        const fingerText = (data?.finger_gesture_text || '').trim()
        const bestText = sequenceText || handText || fingerText
        if (bestText) {
          setInput(bestText)
          setDetectedText(`Detected: ${bestText}`)
        } else {
          setDetectedText('Recognizing gestures...')
        }
      } catch (err) {
        if (!stopped) setDetectedText('Gesture server not reachable')
      } finally {
        if (!stopped) timeoutId = setTimeout(pollGesture, 250)
      }
    }

    pollGesture()

    return () => {
      stopped = true
      if (timeoutId) clearTimeout(timeoutId)
    }
  }, [isCamOpen, apiBase])

  const regenerateSelectedWords = async () => {
    try {
      const response = await fetch('/keypoint_sequence_classifier_label.csv')
      const csvText = await response.text()
      const words = csvText.trim().split('\n').filter(word => word.trim())
      if (words.length < 4) return
      const shuffled = words.sort(() => 0.5 - Math.random())
      const selectedWords = shuffled.slice(0, 4)
      setSelectedWords(selectedWords)
      setSignWords(selectedWords)
      const vocabList = words.join(', ')
      const prompt = signLanguagePrompt.replace('詞彙文件「keypoint_sequence_classifier_label.csv」內容（所有詞彙必須來自此列表，不能添加外部詞彙）', `詞彙文件「keypoint_sequence_classifier_label.csv」內容（所有詞彙必須來自此列表，不能添加外部詞彙）：${vocabList}`)
      generateGeminiReply(prompt)
    } catch (error) {
      console.error('Error loading words:', error)
    }
  }

  useEffect(() => {
    if (hasAutoGeneratedRef.current) return
    hasAutoGeneratedRef.current = true
    regenerateSelectedWords()
  }, [])

  useEffect(() => {
    if (isCamOpen) return
    const expected = selectedWords.join(' ').trim()
    if (!expected) return
    if (input.trim() === expected) {
      regenerateSelectedWords()
    }
  }, [input, selectedWords, isCamOpen])

  const handleSend = (e) => {
    e.preventDefault()
    if (!input.trim()) return
    const expected = selectedWords.join(' ').trim()
    if (!expected || input.trim() !== expected) return
    const userText = input.trim()
    const newEntry = { id: uuidv4(), text: userText, time: new Date().toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'}) }
    setHistory([newEntry, ...history])
    setMessages(prev => ([...prev, { id: uuidv4(), role: 'user', text: userText }]))
    setInput('')
    generateGeminiReply(userText)
  }

  const generateGeminiReply = async (promptText) => {
    if (isCamOpen) return
    const apiKey = process.env.REACT_APP_POE_API_KEY
    const model = process.env.REACT_APP_POE_MODEL || 'grok-4.1-fast-reasoning'
    if (!apiKey) {
      setGenError('Missing Poe API Key, Please set REACT_APP_POE_API_KEY')
      return
    }

    setGenError('')
    setIsGenerating(true)
    try {
      console.log('Sending request to Poe API with prompt:', promptText)
      const resp = await fetch('https://api.poe.com/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model,
          messages: [
            { role: 'user', content: promptText }
          ],
          temperature: 0.7,
          max_tokens: 200
        })
      })
      console.log('Response status:', resp.status)
      if (!resp.ok) {
        const errText = await resp.text()
        console.error('API Error:', errText)
        if (resp.status === 401 || resp.status === 403) {
          throw new Error('Unauthorized. Please check your Poe API key and model access.')
        }
        if (resp.status === 429) {
          throw new Error('Rate limited. Please wait and try again.')
        }
        throw new Error(errText || 'Poe API Error')
      }

      const data = await resp.json()
      console.log('API Response data:', data)
      const reply = data?.choices?.[0]?.message?.content?.trim() || '(No reply)'
      console.log('Extracted reply:', reply)
      const lines = reply.split('\n')
      const signLine = lines.find(line => line.trim().startsWith('手語表達：'))
      if (signLine) {
        const signText = signLine.replace('手語表達：', '').trim()
        const parsedSignWords = signText.split(' ').filter(w => w.trim())
        setSignWords(parsedSignWords)
      }
      setMessages(prev => ([...prev, { id: uuidv4(), role: 'assistant', text: reply }]))
    } catch (err) {
      console.error('Generation error:', err)
      setGenError('Generation failed, please try again later')
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <div className="chat-app">
      {/* 1. Left side sign language history panel */}
      <aside className="app-sidebar">
        <div className="sidebar-header">
          <div className="search-bar">
            <FaSearch />
            <input type="text" placeholder="Search history..." />
          </div>
        </div>
        <div className="history-container">
          <div className="history-label"><FaHistory /> Conversion History</div>
          {history.map(item => (
            <div key={item.id} className="history-card" onClick={() => setInput(item.text)}>
              <div className="history-info">
                <span className="history-text">{item.text}</span>
                <span className="history-time">{item.time}</span>
              </div>
              <FaTrashAlt className="del-btn" />
            </div>
          ))}
        </div>
      </aside>

      {/* 2. 右側主內容區 */}
      <main className="app-main">
        <header className="main-nav">AI Sign-Language Assistant</header>

        <div className="chat-messages">
          {messages.map(msg => (
            <div key={msg.id} className={`chat-bubble ${msg.role}`}>
              {msg.text}
            </div>
          ))}
          {isGenerating && (
            <div className="chat-bubble assistant">Generating...</div>
          )}
          {genError && (
            <div className="chat-error">{genError}</div>
          )}
        </div>

        {/* Figure 3 core optimization: visual feedback area */}
        <section className="sign-visual-section">
          
          {/* 【Key modification】: output Bar with height x3, used to place multiple GIF boxes */}
          <div className="sign-status-bar x3-height">
            <div className="gif-sequence-wrapper">
              {isGenerating ? (
                <span className="placeholder-text">Waiting...</span>
              ) : input && input.trim() === selectedWords.join(' ').trim() ? (
                <div className="gif-flex-container">
                  {/* This corresponds to the combined gif1 + gif2 logic at the bottom of Figure 3 */}
                  {input.split(' ').map((word, i) => (
                    <div key={i} className="gif-box-unit">
                      <div className="gif-placeholder-img">GIF</div>
                      <span className="gif-label">{word}</span>
                    </div>
                  ))}
                </div>
              ) : signWords.length > 0 ? (
                <div className="gif-flex-container">
                  {signWords.map((word, i) => (
                    <div key={i} className="gif-box-unit">
                      <div className="gif-placeholder-img">GIF</div>
                      <span className="gif-label">{word}</span>
                    </div>
                  ))}
                </div>
              ) : (
                <span className="placeholder-text">請輸入文字，此處將顯示手語 GIF 序列</span>
              )}
            </div>
          </div>

          {/* 相機框保持正常比例 */}
          <div className="main-display-box">
            {isCamOpen ? (
              <img
                className="video-stream"
                src={`${apiBase}/stream`}
                alt="Gesture stream"
              />
            ) : (
              <div className="empty-visual">
                <p>Camera is off</p>
                <small>Click the camera icon below to enable real-time recognition</small>
              </div>
            )}
          </div>
        </section>

        {/* 底部輸入控制 */}
        <footer className="control-footer">
          <form className="main-input-group" onSubmit={handleSend}>
            <input 
              type="text" 
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder={isCamOpen ? "Camera mode recognition..." : "Please enter text here..."}
              disabled={isCamOpen || isGenerating}
            />
            <button type="submit" className="icon-btn send-btn" disabled={!input || isGenerating}>
              <FaChevronRight />
            </button>
          </form>
          
          <button 
            className={`mode-toggle-btn ${isCamOpen ? 'cam-active' : ''}`}
            onClick={() => setIsCamOpen(!isCamOpen)}
          >
            {isCamOpen ? <FaKeyboard /> : <FaCamera />}
          </button>
        </footer>
      </main>

      <style>{`
        .chat-app { display: flex; height: 100vh; width: 100vw; overflow: hidden; font-family: sans-serif; background: #fff; }
        
        /* Sidebar 樣式 */
        .app-sidebar { width: 300px; background: #f7f7f8; border-right: 1px solid #ddd; display: flex; flex-direction: column; }
        .sidebar-header { padding: 20px 15px; }
        .search-bar { display: flex; align-items: center; background: white; padding: 10px 15px; border-radius: 8px; border: 1px solid #eee; }
        .search-bar input { border: none; outline: none; margin-left: 10px; width: 100%; }
        .history-container { flex: 1; overflow-y: auto; padding: 10px; }
        .history-label { font-size: 13px; color: #888; margin-bottom: 12px; font-weight: bold; }
        .history-card { background: white; padding: 15px; border-radius: 10px; margin-bottom: 10px; display: flex; justify-content: space-between; align-items: center; cursor: pointer; border: 1px solid #eee; }
        .history-card:hover { border-color: #10a37f; }

        .app-main { flex: 1; display: flex; flex-direction: column; }
        .main-nav { padding: 15px 25px; border-bottom: 1px solid #eee; font-weight: bold; }
        .chat-messages { flex: 1; padding: 15px 25px; overflow-y: auto; display: flex; flex-direction: column; gap: 10px; }
        .chat-bubble { max-width: 75%; padding: 10px 14px; border-radius: 12px; line-height: 1.4; font-size: 14px; }
        .chat-bubble.user { align-self: flex-end; background: #10a37f; color: white; }
        .chat-bubble.assistant { align-self: flex-start; background: #f0f0f0; color: #222; }
        .chat-error { color: #ff4d4f; font-size: 12px; }

        /* 視覺反饋區 */
        .sign-visual-section { padding: 20px; background: #fff; display: flex; flex-direction: column; gap: 15px; }
        
        /* 【關鍵】加高 3 倍的 Bar */
        .sign-status-bar.x3-height { 
          width: 100%; 
          height: 180px; /* 原本約 60px，現在加高到 180px */
          background: #f9f9f9; 
          border: 2px solid #10a37f; 
          border-radius: 15px; 
          display: flex; 
          align-items: center; 
          justify-content: center;
          overflow-x: auto; /* 文字太長時可以橫向捲動 GIF */
          padding: 10px;
        }

        /* GIF 序列排版 */
        .gif-flex-container { display: flex; gap: 15px; padding: 0 10px; }
        .gif-box-unit { display: flex; flex-direction: column; align-items: center; gap: 5px; }
        .gif-placeholder-img { 
          width: 120px; height: 120px; background: #ddd; 
          border-radius: 8px; display: flex; align-items: center; 
          justify-content: center; font-size: 12px; font-weight: bold; color: #666;
        }
        .gif-label { font-size: 14px; font-weight: bold; color: #10a37f; }

        /* 相機展示框比例正常 */
        .main-display-box { 
          width: 100%; height: 350px; background: #1a1a1a; border-radius: 15px; 
          overflow: hidden; display: flex; justify-content: center; align-items: center;
        }
        .video-stream { width: 100%; height: 100%; object-fit: cover; }
        .empty-visual { color: #555; text-align: center; }

        /* 底部輸入控制 */
        .control-footer { padding: 20px; display: flex; gap: 15px; align-items: center; border-top: 1px solid #eee; }
        .main-input-group { flex: 1; background: #f0f0f0; border-radius: 25px; display: flex; padding: 5px 20px; align-items: center; }
        .main-input-group input { flex: 1; border: none; outline: none; background: transparent; padding: 10px; }
        .mode-toggle-btn { width: 50px; height: 50px; border-radius: 15px; border: none; background: #f0f0f0; cursor: pointer; font-size: 20px; }
        .mode-toggle-btn.cam-active { background: #10a37f; color: white; }
        .blinking { color: #ff4d4f; animation: blinker 1.5s linear infinite; }
        @keyframes blinker { 50% { opacity: 0; } }
      `}</style>
    </div>
  )
}