import React, { useState, useRef, useEffect } from 'react'
import { FaChevronRight, FaTrashAlt, FaCamera, FaKeyboard, FaSearch, FaHistory } from 'react-icons/fa'
import { v4 as uuidv4 } from 'uuid'
import { signLanguagePrompt } from './prompt.js'
import './chatBox.css'

export default function ChatBox() {
  const apiBase = process.env.REACT_APP_GESTURE_API || 'http://localhost:5001'
  const hasAutoGeneratedRef = useRef(false)
  const [input, setInput] = useState('')
  const [isCamOpen, setIsCamOpen] = useState(false)
  const [userInfo, setUserInfo] = useState({ nickname: '', email: '' })
  const [detectedText, setDetectedText] = useState('Waiting for sign language signal...')
  const [messages, setMessages] = useState([])
  const [isGenerating, setIsGenerating] = useState(false)
  const [genError, setGenError] = useState('')
  const [selectedWords, setSelectedWords] = useState([])
  const [signWords, setSignWords] = useState([])
  const [fontSize, setFontSize] = useState(() => localStorage.getItem('fontSize') || '100%')
  const [colorMode, setColorMode] = useState(() => localStorage.getItem('colorMode') || 'light')
  
  // Left side sign language conversion history (corresponding to the left side of Figure 3)
  const [history, setHistory] = useState([
    { id: '1', text: '我上課', time: '10:30' },
    { id: '2', text: '謝謝你', time: '09:15' }
  ])

  useEffect(() => {
    if (!isCamOpen) return
    let stopped = false
    let timeoutId = null

    const pollGesture = async () => {
      if (stopped) return
      try {
        const resp = await fetch(`${apiBase}/gesture`)
        if (!resp.ok) throw new Error('Gesture API not available')
        const data = await resp.json()
        const sequenceText = (data?.sequence_gesture_text || '').trim()
        const handText = (data?.hand_sign_text || '').trim()
        const fingerText = (data?.finger_gesture_text || '').trim()
        const bestText = sequenceText || handText || fingerText
        if (bestText) {
          setInput(bestText)
          setDetectedText(`Detected: ${bestText}`)
        } else {
          setDetectedText('Recognizing gestures...')
        }
      } catch (err) {
        if (!stopped) setDetectedText('Gesture server not reachable')
      } finally {
        if (!stopped) timeoutId = setTimeout(pollGesture, 250)
      }
    }

    pollGesture()

    return () => {
      stopped = true
      if (timeoutId) clearTimeout(timeoutId)
    }
  }, [isCamOpen, apiBase])

  const regenerateSelectedWords = async () => {
    try {
      const response = await fetch('/keypoint_sequence_classifier_label.csv')
      const csvText = await response.text()
      const words = csvText.trim().split('\n').filter(word => word.trim())
      if (words.length < 4) return
      const shuffled = words.sort(() => 0.5 - Math.random())
      const selectedWords = shuffled.slice(0, 4)
      setSelectedWords(selectedWords)
      setSignWords(selectedWords)
      const vocabList = words.join(', ')
      const prompt = signLanguagePrompt.replace('詞彙文件「keypoint_sequence_classifier_label.csv」內容（所有詞彙必須來自此列表，不能添加外部詞彙）', `詞彙文件「keypoint_sequence_classifier_label.csv」內容（所有詞彙必須來自此列表，不能添加外部詞彙）：${vocabList}`)
      generateGeminiReply(prompt)
    } catch (error) {
      console.error('Error loading words:', error)
    }
  }

  useEffect(() => {
    // Load user info from localStorage
    const storedUser = localStorage.getItem('user')
    if (storedUser) {
      const userData = JSON.parse(storedUser)
      setUserInfo({
        nickname: userData.nickname || userData.username || 'User',
        email: userData.email || ''
      })
    }

    // Apply color mode from localStorage
    const savedColorMode = localStorage.getItem('colorMode') || 'light'
    setColorMode(savedColorMode)
    if (savedColorMode === 'dark') {
      document.body.classList.add('dark-mode')
    } else {
      document.body.classList.remove('dark-mode')
    }

    // Apply RG-CVD mode
    const savedRgCvdMode = localStorage.getItem('rgCvdMode') === 'true'
    if (savedRgCvdMode) {
      document.body.classList.add('rg-cvd-mode')
    } else {
      document.body.classList.remove('rg-cvd-mode')
    }
  }, [])

  useEffect(() => {
    if (hasAutoGeneratedRef.current) return
    hasAutoGeneratedRef.current = true
    regenerateSelectedWords()
  }, [])

  useEffect(() => {
    if (isCamOpen) return
    const expected = selectedWords.join(' ').trim()
    if (!expected) return
    if (input.trim() === expected) {
      regenerateSelectedWords()
    }
  }, [input, selectedWords, isCamOpen])

  const handleSend = (e) => {
    e.preventDefault()
    if (!input.trim()) return
    const expected = selectedWords.join(' ').trim()
    if (!expected || input.trim() !== expected) return
    const userText = input.trim()
    const newEntry = { id: uuidv4(), text: userText, time: new Date().toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'}) }
    setHistory([newEntry, ...history])
    setMessages(prev => ([...prev, { id: uuidv4(), role: 'user', text: userText }]))
    setInput('')
    generateGeminiReply(userText)
  }

  const generateGeminiReply = async (promptText) => {
    if (isCamOpen) return
    const apiKey = process.env.REACT_APP_POE_API_KEY
    const model = process.env.REACT_APP_POE_MODEL || 'grok-4.1-fast-reasoning'
    if (!apiKey) {
      setGenError('Missing Poe API Key, Please set REACT_APP_POE_API_KEY')
      return
    }

    setGenError('')
    setIsGenerating(true)
    try {
      console.log('Sending request to Poe API with prompt:', promptText)
      const resp = await fetch('https://api.poe.com/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model,
          messages: [
            { role: 'user', content: promptText }
          ],
          temperature: 0.7,
          max_tokens: 200
        })
      })
      console.log('Response status:', resp.status)
      if (!resp.ok) {
        const errText = await resp.text()
        console.error('API Error:', errText)
        if (resp.status === 401 || resp.status === 403) {
          throw new Error('Unauthorized. Please check your Poe API key and model access.')
        }
        if (resp.status === 429) {
          throw new Error('Rate limited. Please wait and try again.')
        }
        throw new Error(errText || 'Poe API Error')
      }

      const data = await resp.json()
      console.log('API Response data:', data)
      const reply = data?.choices?.[0]?.message?.content?.trim() || '(No reply)'
      console.log('Extracted reply:', reply)
      const lines = reply.split('\n')
      const signLine = lines.find(line => line.trim().startsWith('手語表達：'))
      if (signLine) {
        const signText = signLine.replace('手語表達：', '').trim()
        const parsedSignWords = signText.split(' ').filter(w => w.trim())
        setSignWords(parsedSignWords)
      }
      setMessages(prev => ([...prev, { id: uuidv4(), role: 'assistant', text: reply }]))
    } catch (err) {
      console.error('Generation error:', err)
      setGenError('Generation failed, please try again later')
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <div className={`chat-app ${fontSize === '90%' ? 'font-size-90' : fontSize === '125%' ? 'font-size-125' : 'font-size-100'}`}>
      {/* 1. Left side sign language history panel */}
      <aside className="app-sidebar">
        <div className="sidebar-header">
          <div className="search-bar">
            <FaSearch />
            <input type="text" placeholder="Search history..." />
          </div>
        </div>
        <div className="history-container">
          <div className="history-label"><FaHistory /> Conversion History</div>
          {history.map(item => (
            <div key={item.id} className="history-card" onClick={() => setInput(item.text)}>
              <div className="history-info">
                <span className="history-text">{item.text}</span>
                <span className="history-time">{item.time}</span>
              </div>
              <FaTrashAlt className="del-btn" />
            </div>
          ))}
        </div>
      </aside>

      {/* 2. 右側主內容區 */}
      <main className="app-main">
        <header className="main-nav">
          <span>GPT-Sign-Language Assistant</span>
          <div className="header-controls">
            <div className="font-size-controls">
              <button
                type="button"
                className={`font-size-btn size-small ${fontSize === '90%' ? 'active' : ''}`}
                onClick={() => {
                  setFontSize('90%')
                  localStorage.setItem('fontSize', '90%')
                }}
                title="Small (90%)"
              >
                aa
              </button>
              <button
                type="button"
                className={`font-size-btn size-normal ${fontSize === '100%' ? 'active' : ''}`}
                onClick={() => {
                  setFontSize('100%')
                  localStorage.setItem('fontSize', '100%')
                }}
                title="Normal (100%)"
              >
                Aa
              </button>
              <button
                type="button"
                className={`font-size-btn size-large ${fontSize === '125%' ? 'active' : ''}`}
                onClick={() => {
                  setFontSize('125%')
                  localStorage.setItem('fontSize', '125%')
                }}
                title="Large (125%)"
              >
                AA
              </button>
            </div>
            <button
              type="button"
              className="theme-toggle"
              onClick={() => {
                const nextMode = colorMode === 'light' ? 'dark' : 'light'
                setColorMode(nextMode)
                localStorage.setItem('colorMode', nextMode)
                if (nextMode === 'dark') {
                  document.body.classList.add('dark-mode')
                } else {
                  document.body.classList.remove('dark-mode')
                }
              }}
              aria-label={colorMode === 'light' ? 'Switch to dark mode' : 'Switch to light mode'}
              title={colorMode === 'light' ? 'Dark mode' : 'Light mode'}
            >
              {colorMode === 'light' ? '🌙' : '☀️'}
            </button>
          </div>
        </header>

        <div className="chat-messages">
          {messages.map(msg => (
            <div key={msg.id} className={`chat-bubble ${msg.role}`}>
              {msg.text}
            </div>
          ))}
          {isGenerating && (
            <div className="chat-bubble assistant">Generating...</div>
          )}
          {genError && (
            <div className="chat-error">{genError}</div>
          )}
        </div>

        {/* Figure 3 core optimization: visual feedback area */}
        <section className="sign-visual-section">
          
          {/* 【Key modification】: output Bar with height x3, used to place multiple GIF boxes */}
          <div className="sign-status-bar x3-height">
            <div className="gif-sequence-wrapper">
              {isGenerating ? (
                <span className="placeholder-text">Waiting...</span>
              ) : input && input.trim() === selectedWords.join(' ').trim() ? (
                <div className="gif-flex-container">
                  {/* This corresponds to the combined gif1 + gif2 logic at the bottom of Figure 3 */}
                  {input.split(' ').map((word, i) => (
                    <div key={i} className="gif-box-unit">
                      <div className="gif-placeholder-img">WEBP</div>
                      <span className="gif-label">{word}</span>
                    </div>
                  ))}
                </div>
              ) : signWords.length > 0 ? (
                <div className="gif-flex-container">
                  {signWords.map((word, i) => (
                    <div key={i} className="gif-box-unit">
                      <div className="gif-placeholder-img">WEBP</div>
                      <span className="gif-label">{word}</span>
                    </div>
                  ))}
                </div>
              ) : (
                <span className="placeholder-text">請輸入文字，此處將顯示手語 GIF 序列</span>
              )}
            </div>
          </div>

          {/* 相機框保持正常比例 */}
          {isCamOpen && (
            <div className="main-display-box">
              <img
                className="video-stream"
                src={`${apiBase}/stream`}
                alt="Gesture stream"
              />
            </div>
          )}
        </section>

        {/* 底部輸入控制 */}
        <footer className="control-footer">
          <form className="main-input-group" onSubmit={handleSend}>
            <input 
              type="text" 
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder={isCamOpen ? "相機模式辨識中..." : "請在此輸入文字..."}
              readOnly
            />
            <button type="submit" className="icon-btn send-btn" disabled={!input || isGenerating}>
              <FaChevronRight />
            </button>
          </form>
          
          <button 
            className={`mode-toggle-btn ${isCamOpen ? 'cam-active' : ''}`}
            onClick={() => setIsCamOpen(!isCamOpen)}
          >
            {isCamOpen ? <FaKeyboard /> : <FaCamera />}
          </button>
        </footer>
      </main>
    </div>
  )
}